env:
  es6: true
  node: true
extends: 'node'
parserOptions:
  ecmaVersion: 2015
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  
  no-console: off
  import/no-commonjs: off
  import/no-nodejs-modules: off
  prefer-const: off
  no-sync: off
  eqeqeq: off
  no-process-exit: off
  class-methods-use-this: off
  arrow-body-style:
    - error
    - always
