pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install --production
  displayName: 'Run npm install in the project'

- script: |
    npm install -g pkg
  displayName: 'Install pkg globally'

- script: |
    mkdir dist && pkg --out-path dist .
  displayName: 'Build binary for Linux'
