trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

stages:

  # First stage: set up the environment: install Node.js and the dependencies
  - stage: setup
    displayName: Setup environment
    jobs:
      - job: setup
        steps:
          # Install Node.js
          - task: NodeTool@0
            inputs:
              versionSpec: 10.16.x
            displayName: 'Install Node.js'
          # Install dependencies
          - script: |
              npm install
            displayName: 'Install dependencies'
  
  # Run tests
  - stage: tests
    displayName: Run tests
    dependsOn: [setup]
    condition: succeeded('setup')
    jobs:
      - job: tests
        steps:
          # Run tests
          - script: |
              npm run test-ci
            displayName: 'Run tests'
          
          # Publish results
          - task: PublishTestResults@2
            condition: succeededOrFailed()
            inputs:
              testRunner: JUnit
              testResultsFiles: '$(System.DefaultWorkingDirectory)/test-results.xml'
          
          # Publish coverage
          - task: PublishCodeCoverageResults@1
            inputs: 
              codeCoverageTool: Cobertura
              summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
              reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'  
