pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install --production
  displayName: 'Run npm install in the project'

- script: |
    npm install -g pkg
  displayName: 'Install pkg globally'

- script: |
    'mkdir dist && pkg --targets node8-linux-x64,node8-macos-x64,node8-win-x64 --out-path dist .'
  displayName: 'Build binaries with pkg for Linux, macOS and Windows'

- task: CopyFiles@2
  inputs:
    contents: 'dist/*'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    cleanTargetFolder: true
  displayName: 'Copy output to artifacts staging directory'

- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'
